var nomedavariavel="valor da variavel";
var outravariavel='valor da outra variavel';
var variavel=15;
var variavelvouganharnamega=false;
var variavelindefinida;
console.log(nomedavariavel);
var teste="Aprender";
console.log(teste);
teste="novovalor";
console.log(teste);